import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LcHeader } from "./+common/components/feature/header/LcHeader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Litecard mall",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </head>
      <body className={inter.className}>
        <LcHeader>
          <main className="mt-20">
            <div className="p-4 md:p-8">{children}</div>
          </main>
        </LcHeader>
      </body>
    </html>
  );
}
