import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LcHeader } from "./+components/feature/LcHeader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </head>
      <body className={inter.className}>
        <LcHeader />
        <main>
          <div className="p-4 md:p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
